trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Étape pour incrémenter la version dans le fichier version.txt
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Chemin vers le fichier version.txt
      $versionFilePath = "$(Build.SourcesDirectory)/version.txt"
      
      # Lire la version actuelle à partir du fichier version.txt
      $version = Get-Content $versionFilePath
      
      # Diviser la version en parties : majeure, mineure, patch
      $versionParts = $version -split '\.'
      $major = [int]$versionParts[0]
      $minor = [int]$versionParts[1]
      $patch = [int]$versionParts[2]
      
      # Afficher la version actuelle
      echo "Version actuelle : $major.$minor.$patch"
      
      # Si un changement du numéro mineur est détecté, incrémenter le mineur et remettre le patch à zéro
      if ($env:NEW_MINOR -and $minor -ne $env:NEW_MINOR) {
          echo "Incrémentation de la version mineure..."
          $minor = [int]$env:NEW_MINOR
          $patch = 0
          $newVersion = "$major.$minor.$patch-rc"
      } else {
          echo "Aucune modification de la version mineure, incrémentation du patch..."
          $patch++
          $newVersion = "$major.$minor.$patch"
      }

      # Afficher la nouvelle version
      echo "Nouvelle version : $newVersion"
      
      # Mettre à jour le fichier version.txt avec la nouvelle version
      Set-Content -Path $versionFilePath -Value $newVersion
      
      # Enregistrer la nouvelle version dans la variable de build
      echo "##vso[task.setvariable variable=version]$newVersion"
  displayName: 'Incrémenter le patch dans version.txt'

# Étape pour valider et pousser les modifications dans GitHub
- script: |
    git config --global user.name "jamil"
    git config --global user.email "abidijamil@gmail.com"
    git remote set-url origin "https://$(GITHUB_TOKEN)@github.com/jamilabidi/pipelines-java"

    # Tirer les dernières modifications de la branche distante avant de pousser
    git pull origin main --rebase

    # Ajouter les modifications dans version.txt
    git add version.txt
    
    # Valider les modifications
    git commit -m "Incrémentation de la version à $(version)"
    
    # Pousser les modifications vers la branche main
    git push origin HEAD:main
  displayName: 'Valider et pousser le fichier de version'
